### ISSUE TITLE
Log in page does not scale properly 

### ISSUE THREAD

**Issue by mke9m** [vorcil/myvote#17]
Log in page does not scale properly on phones.

**Comment by lukesUbuntu** [comment]
@maent45

**Comment by maent45** [comment]
yea I've noticed that.. hang on will fix it up now

**Comment by vorcil** [comment]
Issue resolved?

**Comment by lukesUbuntu** [comment]
Yup has been fixed on f94cfeefc8d9a23ff1c03a5e96fced954bf225f7 closing
